// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbZznxsD2-c8qVRFlkMU1def2Uf0-eBY',
    appId: '1:369160437726:web:1cb31b1ba77e723edae74f',
    messagingSenderId: '369160437726',
    projectId: 'spotify-clone-09',
    authDomain: 'spotify-clone-09-7aa7e.firebaseapp.com',
    storageBucket: 'spotify-clone-09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJQeGQg7_dUETK5Rn96pAv8bcqrxOjXs',
    appId: '1:369160437726:android:9adeafe0860598e0dae74f',
    messagingSenderId: '369160437726',
    projectId: 'spotify-clone-09',
    storageBucket: 'spotify-clone-09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACmh-fcGRlRhrDHxCaUKzFIcs04OEzyuk',
    appId: '1:369160437726:ios:b2509de0135c40efdae74f',
    messagingSenderId: '369160437726',
    projectId: 'spotify-clone-09',
    storageBucket: 'spotify-clone-09.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACmh-fcGRlRhrDHxCaUKzFIcs04OEzyuk',
    appId: '1:369160437726:ios:b2509de0135c40efdae74f',
    messagingSenderId: '369160437726',
    projectId: 'spotify-clone-09',
    storageBucket: 'spotify-clone-09.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlbZznxsD2-c8qVRFlkMU1def2Uf0-eBY',
    appId: '1:369160437726:web:7fd36abbf08ea0ffdae74f',
    messagingSenderId: '369160437726',
    projectId: 'spotify-clone-09',
    authDomain: 'spotify-clone-09-7aa7e.firebaseapp.com',
    storageBucket: 'spotify-clone-09.firebasestorage.app',
  );
}
